@startuml ProductType
skinparam maxMessageSize 100
skinparam wrapWidth 400

[*] --> Active : New product type is created.

Active : The product type is active and used for organizing products.
Active --> Inactive : Product type is deactivated.

Inactive : The product type is not currently used.
Inactive --> Active : Product type is reactivated.

Inactive --> [*] : Product type is permanently removed.

@enduml